---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: sort-simple-yaml
        files: ^vars/(.*).yml$
      - id: check-added-large-files
        args: ['--maxkb=6000']

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.1
    hooks:
      - id: editorconfig-checker

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
        args: ['-x']
        files: \.(sh|bash|zsh|ksh)$
